### ISSUE TITLE
Add an LLMPipeline class for evaluation

### ISSUE THREAD

**Issue by kuraisle** [Health-Informatics-UoN/lettuce#60]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

We're testing different LLMs for their performance on the drug dataset. For the evaluation framework, we need an `LLMPipeline` class that inherits from `SingleResultPipeline` and can be used in `SingleResultPipelineTest`.

It needs a `.run()` method for the input data, and should initialise with a model and a prompt template to provide with the input data.

Could we have a commit for each task to make it clearer what's happening, please?

### Acceptance Criteria

- [ ] Carrot-Assistant/evaluation/pipelines.py present
- [ ] LLMPipeline class created in pipelines.py
- [ ] LLMPipeline .run() passes tests 

### Tasks

- [ ] create file for pipelines
- [ ] create LLMPipeline class
    - [ ] initialises with argument for an LLM (maybe reuse LLMModel enum in options/pipeline_options.py?)
    - [ ] initialises with argument for prompt template
- [ ] implement LLMPipeline.run()
- [ ] LLMPipeline tests
    - [ ] .run() returns a single string
    - [ ] loads a model?
- [ ] Documentation.

### Confirm creation

- [x] This issue is ready
