### ISSUE TITLE
Make `EvaluationFramework` work

### ISSUE THREAD

**Issue by kuraisle** [Health-Informatics-UoN/lettuce#68]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

Currently the `EvaluationFramework` class doesn't do anything. We need to make it useful.

The behaviour we need is:
- The class loads data from a file. The data will contain the input and expected output
- The class will initialise with a list of `PipelineTest`s
- run_evaluations should run each input through each `PipelineTest` and evaluates the output
  - I would suggest all inputs are run through a `TestPipeline` and then the pipeline is dropped for RAM purposes, particularly with LLM pipelines
- After running, `_save_evaluations()` should save the results to an output file

### Acceptance Criteria

- [ ] EvaluationFramework has data loaders
- [ ] A list of `PipelineTest` added to `EvaluationFramework.__init__()`
- [ ] `EvaluationFramework.run_evaluations()` runs input
- [ ] `EvaluationFramework.run_evaluations()` evaluates output
- [ ] `EvaluationFramework._save_evaluations()` saves json of the output of running evaluation
- [ ] Add a drop method to pipelines to accommodate dropping LLMPipelines
- [ ] Tests pass.
- [ ] Documentation added.

### Tasks

- [ ] Update parameters
- [ ] write methods
- [ ] Unit tests.
- [ ] Documentation.

### Confirm creation

- [x] This issue is ready
