### ISSUE TITLE
Descriptions on metrics

### ISSUE THREAD

**Issue by kuraisle** [Health-Informatics-UoN/lettuce#69]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

Metrics in the evaluation framework should have names and descriptions so they can be read later

### Acceptance Criteria

- [x] Add name property to metric class
- [x] Add description property to metric class
- [x] Tests pass.
- [x] Documentation added.

### Tasks

Acceptance critera

### Confirm creation

- [x] This issue is ready
