### ISSUE TITLE
Function for fetching a list of related and ancestor concepts

### ISSUE THREAD

**Issue by kuraisle** [Health-Informatics-UoN/lettuce#78]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

The function that fetches related and ancestor concepts will be reused for multiple metrics, so should be encapsulated separately

### Acceptance Criteria

- [x] Relevant concepts are fetched from database
- [x] Function output is usable for the metric paradigm
- [x] Tests pass.
- [x] Documentation added.

### Tasks

- [ ] Use ORM to fetch concepts
- [ ] Filter relationships
- [ ] Levels of hierarchy up
- [ ] Function returns a list of concept names (List[str])
- [ ] Unit tests.
- [ ] Documentation.

### Confirm creation

- [x] This issue is ready
