### ISSUE TITLE
Separate CLI and service

### ISSUE THREAD

**Issue by kuraisle** [Health-Informatics-UoN/lettuce#84]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

Lettuce currently passes round an argparse namespace for everything. This functionality can be kept in a CLI, but the rest should move to a service configured through environment variables for easier deployment

### Acceptance Criteria

- [x] Functions using the `opt` objects should no longer accept those
- [x] A separate `cli` script can use the args from `opt`
- [x] A separate API can just use the parameters in requests

### Tasks

- [x] Remove `opt` from functions
- [x] Create CLI
- [x] API should still work

### Confirm creation

- [x] This issue is ready
