### ISSUE TITLE
Clean up repo

### ISSUE THREAD

**Issue by kuraisle** [Health-Informatics-UoN/lettuce#85]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

If people are going to be deploying this, it needs some maintenance. Old versions are kept in folders. These aren't necessary, and are archived in devops in any case. The code needs to be consistently formatted to make future PRs easier to read.

### Acceptance Criteria

- [x] No more old folders
- [x] Renamed `/Carrot-Assistant`
- [x] Black formatted code

### Tasks

- [ ] Task A.
- [ ] Task B.
- [ ] Unit tests.
- [ ] Documentation.

### Confirm creation

- [x] This issue is ready
