### ISSUE TITLE
Remake docs

### ISSUE THREAD

**Issue by kuraisle** [Health-Informatics-UoN/lettuce#86]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

Docs should have instructions for deployment using containers, and setting up dev environment. See Hutch docs

### Acceptance Criteria

- [ ] Documentation includes containerized deployment instructions
- [ ] Documentation describes usage
- [ ] Documentation includes dev environment

### Tasks

- [ ] Write docs
- [ ] Integrate into old docs

### Confirm creation

- [x] This issue is ready
