### ISSUE TITLE
CI pytest

### ISSUE THREAD

**Issue by kuraisle** [Health-Informatics-UoN/lettuce#91]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

If it's getting deployed, we should move to CI for released images. This means we should be able to make better assurances about what people are running, including tests upon pull request.

### Acceptance Criteria

- [ ] Workflow for testing on PR
  - [ ] skip LLM portions with `pytest.skipif()` because they're too slow
  - [ ] skip any database tests as well
- [ ] Workflow for image build

### Tasks

- [ ] Write build test workflow
- [ ] tag llm tests so they don't get run in github actions
- [ ] Add `pytest-cov` and `coverage` to `test` dependencies
- [ ] Add code coverage commenting workflow
- [ ] Write test workflow

### Confirm creation

- [x] This issue is ready
