### ISSUE TITLE
Vector similarity metric

### ISSUE THREAD

**Issue by kuraisle** [Health-Informatics-UoN/lettuce#94]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

A quick and dirty metric for how well an embeddings model matches would be simply to calculate vector similarity between an input and desired output

### Acceptance Criteria

- [x] `VectorSimilarityMetric` exists
- [ ] `EmbeddingPipeline` exists
- [ ] `EmbeddingPipeline` accepts arbitrary embedding model and calculates embeddings
- [ ] `VectorSimilarityMetric` accepts arbitrary embedding model and calculates embeddings
- [ ] `VectorSimilarityMetric` can be configured to run
    - dot product
    - cosine distance

### Tasks

- [x] Create `VectorSimilarityMetric`, inheriting from SingleResultMetric
- [x] Create `EmbeddingPipeline`
- [x] Have `EmbeddingPipeline` calculate the embedding for the input
- [x] Have `VectorSimilarityMetric` calculate the embedding for the desired output
- [x] Create functions for dot product and cosine distance
- [x] Add calculate method for VectorSimilarityMetric that calculates either dot product or cosine distance

### Confirm creation

- [x] This issue is ready
