### ISSUE TITLE
Implement RAG pipeline for evaluation

### ISSUE THREAD

**Issue by kuraisle** [Health-Informatics-UoN/lettuce#97]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

We've demonstrated that vector search gets right(ish) concepts off the bat (see paper). We have yet to directly compare a RAG pipeline using a functioning vector search performs any better than an LLM alone. We need a RAG pipeline for evaluation so we can directly compare.

### Acceptance Criteria

- [x] RAGPipeline class exists in evaluation/pipelines
- [x] RAGPipeline takes an input, performs vector search and takes *n* top results
- [x] RAGPipeline uses vector search results for RAG
- [x] RAGPipeline returns a single result

### Tasks

- [x] Create RAGPipeline class
- [x] Give class prompt, embedding model and llm arguments
- [ ] Tests for RAGPipeline class and methods
- [x] Try it out on example dataset (do not commit)

### Confirm creation

- [x] This issue is ready
